# Generated by Django 5.0.6 on 2026-04-24 16:49

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ENTERPRISE', 'Enterprise Leadership'), ('INNOVATION', 'Innovation')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', tinymce.models.HTMLField(blank=True, help_text='Short description (2–3 sentences).')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('eyebrow', models.CharField(blank=True, help_text='Small uppercase label above the page title, e.g. "EXECUTIVE PROFILE".', max_length=80)),
                ('intro', tinymce.models.HTMLField(blank=True, help_text='Optional lead paragraph under the title.')),
                ('seo_title', models.CharField(blank=True, max_length=120)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_headline', models.CharField(default='Leading HR Transformation at Scale, Pioneering Personal AI Systems', max_length=200)),
                ('homepage_subheadline', tinymce.models.HTMLField(blank=True, help_text='One short paragraph under the homepage headline.')),
                ('enterprise_section_intro', tinymce.models.HTMLField(blank=True, help_text='Intro paragraph above the three enterprise pillars.')),
                ('innovation_section_intro', tinymce.models.HTMLField(blank=True, help_text='Intro paragraph above the three innovation highlights.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='NarrativeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('eyebrow', models.CharField(blank=True, help_text='Optional small label above heading.', max_length=80)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', tinymce.models.HTMLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='website.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
