# Generated by Django 5.0.6 on 2026-04-24 17:07

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ENTERPRISE', 'Enterprise'), ('INNOVATION', 'Innovation')], max_length=20)),
                ('summary', models.CharField(help_text='Shown on the case studies index. One or two sentences.', max_length=400)),
                ('problem', tinymce.models.HTMLField(help_text='The strategic or operational problem. Written for an executive reader.')),
                ('role', tinymce.models.HTMLField(help_text='Your role, remit, and reporting context.')),
                ('approach', tinymce.models.HTMLField(help_text='How you approached the problem. Sequencing, decisions, tradeoffs.')),
                ('outcome', tinymce.models.HTMLField(help_text='The measured result. Quantify where possible.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers sort first on the index page.')),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=120)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-published_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_subheadline',
            field=tinymce.models.HTMLField(blank=True, help_text='Short positioning statement under the headline. Should define enterprise leadership scope and systems-thinking approach. 2–3 sentences max.', verbose_name='Homepage positioning statement'),
        ),
    ]
