# Generated by Django 5.0.6 on 2026-04-24 17:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_casestudy_alter_siteconfig_homepage_subheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('summary', models.CharField(blank=True, help_text='One-line framing shown under the function title.', max_length=300)),
                ('responsibilities', tinymce.models.HTMLField(help_text='What this function leads.')),
                ('systems_led', tinymce.models.HTMLField(help_text='Systems, tools, and programs owned.')),
                ('organizational_role', tinymce.models.HTMLField(help_text='How this function fits into the organization.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', tinymce.models.HTMLField(blank=True, help_text='Scale of responsibility — employees, systems, divisions.')),
                ('impact', tinymce.models.HTMLField(blank=True, help_text='What the function is measured on; transformation outcomes.')),
            ],
            options={
                'verbose_name': 'Enterprise Overview',
                'verbose_name_plural': 'Enterprise Overview',
            },
        ),
    ]
