# Generated by Django 5.0.6 on 2026-04-24 17:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_enterprisefunction_enterpriseoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', tinymce.models.HTMLField(blank=True, help_text='Page lead paragraph. Keep brief.')),
                ('beacon_positioning', tinymce.models.HTMLField(blank=True, help_text='What Beacon Innovation, LLC is and why it exists separately from any enterprise role.', verbose_name='Beacon Innovation positioning')),
                ('wlj_overview', tinymce.models.HTMLField(blank=True, help_text='What WLJ is, why it was built, who it is for.', verbose_name='Whole Life Journey overview')),
                ('architecture_caption', tinymce.models.HTMLField(blank=True, help_text='Paragraph accompanying the Data → Signals → Decisions diagram. Explain the three stages in plain language.')),
                ('chief_of_staff', tinymce.models.HTMLField(blank=True, help_text='The AI layer as an executive Chief of Staff — not a chatbot metaphor.', verbose_name='AI Chief of Staff concept')),
            ],
            options={
                'verbose_name': 'Innovation Overview',
                'verbose_name_plural': 'Innovation Overview',
            },
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='system_integration',
            field=tinymce.models.HTMLField(blank=True, help_text='Closing paragraph at the bottom of the Enterprise Leadership page. Explain how Compensation, HRIS, and Payroll operate as one system — not three parallel jobs.', verbose_name='How the system works together'),
        ),
    ]
