# Generated by Django 5.0.6 on 2026-04-24 17:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_innovationoverview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationoverview',
            name='practical_example',
            field=tinymce.models.HTMLField(blank=True, help_text='A concrete scenario showing the pipeline producing one decision (e.g. prioritizing a quick task before a meeting). Grounds the abstract architecture in real use.', verbose_name='Architecture — in-practice example'),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='what_this_demonstrates',
            field=tinymce.models.HTMLField(blank=True, help_text='Closing section. What the WLJ work demonstrates about the author: systems thinking, AI application, cross-domain integration, focus on decision-making.', verbose_name='What this demonstrates'),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='wlj_positioning',
            field=models.CharField(blank=True, help_text='One-line framing statement rendered as a pull-quote above the WLJ overview. Keep to a single sentence or two short sentences.', max_length=300, verbose_name='WLJ positioning line'),
        ),
    ]
