# Generated by Django 5.0.6 on 2026-04-24 17:59

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_innovationoverview_practical_example_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('deck', models.CharField(blank=True, help_text='Short subtitle / summary — shown under the title and on index cards.', max_length=300)),
                ('eyebrow', models.CharField(blank=True, help_text='Category label (e.g. "COMPENSATION", "HRIS", "SYSTEMS").', max_length=40)),
                ('lead', tinymce.models.HTMLField(blank=True, help_text='Opening paragraph — the argument in one paragraph. Serif lead styling.')),
                ('closing', tinymce.models.HTMLField(blank=True, help_text='Final closing paragraph. Rendered below the sections.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers sort first on the index page.')),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=120)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', '-published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerspectiveSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.perspective')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
