# Generated by Django 5.0.6 on 2026-04-24 21:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_perspective_perspectivesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positioning_line', models.CharField(blank=True, help_text='One line below the name at the top. Positioning, not title.', max_length=300)),
                ('executive_summary', tinymce.models.HTMLField(blank=True, help_text='2–3 lines. Do not duplicate the Enterprise Leadership page.')),
                ('current_role_title', models.CharField(blank=True, max_length=200)),
                ('current_role_org', models.CharField(blank=True, max_length=200)),
                ('current_role_dates', models.CharField(blank=True, help_text='e.g. "2023 — Present"', max_length=100)),
                ('current_role_bullets', tinymce.models.HTMLField(blank=True, help_text='4–6 bullets. Use the list button in the editor. Declarative verbs, no "responsible for".')),
                ('prior_roles', tinymce.models.HTMLField(blank=True, help_text='Condensed — one or two lines each. No bullet list for prior roles.')),
                ('education', tinymce.models.HTMLField(blank=True)),
                ('key_impact', tinymce.models.HTMLField(blank=True, help_text='Optional. Bulleted.', verbose_name='Key impact highlights')),
            ],
            options={
                'verbose_name': 'Resume Page',
                'verbose_name_plural': 'Resume Page',
            },
        ),
    ]
