# Generated by Django 5.0.6 on 2026-04-24 21:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_resumepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', tinymce.models.HTMLField(blank=True, help_text='Lead paragraph under the title.')),
                ('conversation_label', models.CharField(default='Request a conversation', max_length=100)),
                ('conversation_blurb', models.CharField(blank=True, help_text='One short line under the label.', max_length=300)),
                ('conversation_href', models.CharField(default='mailto:', help_text='mailto: link or URL (Calendly, etc.).', max_length=500)),
                ('resume_label', models.CharField(default='Request a resume', max_length=100)),
                ('resume_blurb', models.CharField(blank=True, max_length=300)),
                ('resume_href', models.CharField(default='mailto:', help_text='mailto: link the requester uses to ask for a tailored resume URL.', max_length=500)),
            ],
            options={
                'verbose_name': 'Connect Page',
                'verbose_name_plural': 'Connect Page',
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('SUMMARY', 'Executive Summary'), ('CURRENT_ROLE', 'Current Role'), ('PRIOR_ROLES', 'Prior Roles'), ('EDUCATION', 'Education & Certifications'), ('HIGHLIGHTS', 'Key Impact Highlights'), ('CUSTOM', 'Custom Section')], max_length=30)),
                ('heading', models.CharField(blank=True, help_text='Override the default heading for this section type. Required if type=CUSTOM.', max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL identifier, e.g. "general", "hr-ops", "total-rewards".', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Short label shown as the deck under the name (e.g. "HR Operations").', max_length=200)),
                ('type', models.CharField(choices=[('HR_OPS', 'HR Operations'), ('TOTAL_REWARDS', 'Total Rewards'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to take the URL offline without deleting the content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ResumePage',
        ),
        migrations.AddField(
            model_name='resumesection',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.resumeversion'),
        ),
    ]
