# Generated by Django 5.0.6 on 2026-05-01 01:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_connectpage_resumesection_resumeversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='homepage_vision',
            field=tinymce.models.HTMLField(blank=True, help_text='Leadership philosophy block rendered between the hero and the enterprise/innovation split. Use multiple paragraphs.', verbose_name='Homepage vision section'),
        ),
    ]
