# Generated by Django 5.0.6 on 2026-05-01 01:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_siteconfig_homepage_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enterprise_section_closing',
            field=tinymce.models.HTMLField(blank=True, help_text='Closing statement below the three enterprise pillars on the homepage.'),
        ),
    ]
