# Generated by Django 5.0.6 on 2026-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_siteconfig_enterprise_section_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='homepage_positioning_line',
            field=models.CharField(blank=True, help_text='One bridge sentence rendered between the headline and the supporting paragraph. Plain text, no formatting. Sized between headline and body so the eye reads it as a natural extension of the headline.', max_length=300, verbose_name='Homepage positioning line'),
        ),
    ]
