# Generated by Django 5.0.6 on 2026-05-03 17:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_siteconfig_homepage_positioning_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpage',
            name='form_prelude',
            field=models.CharField(blank=True, default='If you’d like to connect, share a few details below.', help_text='Appears on the Connect page as the bridge sentence above the contact form.', max_length=300),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='success_body',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Connect page after a successful form submission, as the paragraph below the confirmation heading.'),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='success_heading',
            field=models.CharField(blank=True, default='Thank you — I’ve received your message.', help_text='Appears on the Connect page after a successful form submission, as the H2 of the confirmation block.', max_length=200),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='function_section_heading',
            field=models.CharField(blank=True, default='What I lead', help_text='Appears on the Enterprise Leadership page as the H2 heading above the three function blocks (Compensation, HRIS, Payroll).', max_length=200),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='hero_heading',
            field=models.CharField(blank=True, default='Running HR operations at scale', help_text='Appears on the Enterprise Leadership page hero as the H1 headline.', max_length=200),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='hero_lead',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Enterprise Leadership page hero, below the headline, as the supporting paragraph.', verbose_name='Hero lead paragraph'),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='system_integration_heading',
            field=models.CharField(blank=True, default='How the system works together', help_text='Appears on the Enterprise Leadership page as the H2 heading of the closing section.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='hero_heading',
            field=models.CharField(blank=True, default='Innovation & Systems Design', help_text='Appears on the Innovation page hero as the H1 headline.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='wlj_case_study_link_label',
            field=models.CharField(blank=True, default='See how this operates in practice → WLJ Case Study', help_text='Appears at the bottom of the Innovation page as the link to the WLJ case study.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enterprise_column_heading',
            field=models.CharField(blank=True, default='Running HR operations that people can depend on', help_text='Appears on the homepage as the H2 heading of the Enterprise Leadership column.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='innovation_column_heading',
            field=models.CharField(blank=True, default='Designing personal AI systems', help_text='Appears on the homepage as the H2 heading of the Innovation column.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='read_profile_link_label',
            field=models.CharField(blank=True, default='Read the executive profile →', help_text='Appears at the bottom of the homepage as the link to the Executive Profile page.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vision_heading',
            field=models.CharField(blank=True, default='How HR operations should work', help_text='Appears on the homepage Vision section as the H2 heading (above the Vision paragraphs).', max_length=200),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='conversation_blurb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='conversation_href',
            field=models.CharField(blank=True, default='mailto:', max_length=500),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='conversation_label',
            field=models.CharField(blank=True, default='Request a conversation', max_length=100),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Connect page hero, below the headline, as the lead paragraph.'),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='resume_href',
            field=models.CharField(blank=True, default='mailto:', max_length=500),
        ),
        migrations.AlterField(
            model_name='connectpage',
            name='resume_label',
            field=models.CharField(blank=True, default='Request a resume', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpriseoverview',
            name='impact',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Enterprise Leadership page as the body of the Impact section.'),
        ),
        migrations.AlterField(
            model_name='enterpriseoverview',
            name='scope',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Enterprise Leadership page as the body of the Scope section.'),
        ),
        migrations.AlterField(
            model_name='enterpriseoverview',
            name='system_integration',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Enterprise Leadership page as the body of the closing section. Explain how Compensation, HRIS, and Payroll operate as one system — not three parallel jobs.', verbose_name='Closing section body'),
        ),
        migrations.AlterField(
            model_name='innovationoverview',
            name='beacon_positioning',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Innovation page as the body of the Beacon Innovation, LLC section.', verbose_name='Beacon Innovation positioning'),
        ),
        migrations.AlterField(
            model_name='innovationoverview',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the Innovation page hero, below the headline, as the lead paragraph.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Appears in the footer of every page as the contact email link.', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='enterprise_section_closing',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the homepage Enterprise Leadership column as the closing block below the three pillars.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='enterprise_section_intro',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the homepage Enterprise Leadership column as the intro paragraph above the three pillars.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_headline',
            field=models.CharField(default='Leading HR Transformation at Scale, Pioneering Personal AI Systems', help_text='Appears on the homepage hero as the large H1 headline.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_positioning_line',
            field=models.CharField(blank=True, help_text='Appears on the homepage hero, between the headline and the supporting paragraph. One sentence; plain text. Sized between headline and body so the eye reads it as a natural extension of the headline.', max_length=300, verbose_name='Homepage positioning line'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_subheadline',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the homepage hero, below the positioning line, as the supporting paragraph. Should define enterprise leadership scope and systems-thinking approach. 2–3 sentences max.', verbose_name='Homepage positioning statement'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_vision',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the homepage between the hero and the enterprise/innovation split. The body of the Vision section. Use multiple paragraphs.', verbose_name='Homepage vision section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='innovation_section_intro',
            field=tinymce.models.HTMLField(blank=True, help_text='Appears on the homepage Innovation column as the intro paragraph above the three highlights.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Appears in the footer as the LinkedIn link (opens in new tab).'),
        ),
    ]
