# Generated by Django 5.0.6 on 2026-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_connectpage_form_prelude_connectpage_success_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisefunction',
            name='platforms_and_tools_label',
            field=models.CharField(blank=True, default='PLATFORMS AND TOOLS', help_text='The small uppercase label rendered above the "Systems Led" block on the Enterprise Leadership page. Edit per function. Leave blank to fall back to "PLATFORMS AND TOOLS".', max_length=80, verbose_name='"Systems Led" section label'),
        ),
        migrations.AddField(
            model_name='enterprisefunction',
            name='role_and_accountability_label',
            field=models.CharField(blank=True, default='ROLE AND ACCOUNTABILITY', help_text='The small uppercase label rendered above the "Role in the Organization" block on the Enterprise Leadership page. Edit per function. Leave blank to fall back to "ROLE AND ACCOUNTABILITY".', max_length=80, verbose_name='"Role in the Organization" section label'),
        ),
    ]
