# Generated by Django 5.0.6 on 2026-05-04 13:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_enterprisefunction_platforms_and_tools_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudiesIndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_eyebrow', models.CharField(blank=True, default='Case Studies', help_text='Small uppercase label above the H1 on the Case Studies index.', max_length=80)),
                ('page_title', models.CharField(blank=True, default='Selected work', help_text='H1 at the top of the Case Studies index.', max_length=200)),
                ('page_lead', tinymce.models.HTMLField(blank=True, help_text='Lead paragraph below the H1 on the Case Studies index. Leave blank to fall back to the design-time default.')),
                ('read_more_label', models.CharField(blank=True, default='Read case study →', help_text='Per-card link text on the Case Studies index ("Read case study →").', max_length=60)),
                ('empty_state_label', models.CharField(blank=True, default='No published case studies yet.', help_text='Message shown when there are zero published case studies.', max_length=120)),
            ],
            options={
                'verbose_name': 'Case Studies Index Page',
                'verbose_name_plural': 'Case Studies Index Page',
            },
        ),
        migrations.CreateModel(
            name='PerspectivesIndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_eyebrow', models.CharField(blank=True, default='Perspectives', help_text='Small uppercase label above the H1 on the Perspectives index.', max_length=80)),
                ('page_title', models.CharField(blank=True, default='Perspectives', help_text='H1 at the top of the Perspectives index.', max_length=200)),
                ('page_lead', tinymce.models.HTMLField(blank=True, help_text='Lead paragraph below the H1 on the Perspectives index. Leave blank to fall back to the design-time default.')),
                ('read_more_label', models.CharField(blank=True, default='Read →', help_text='Per-card link text on the Perspectives index.', max_length=60)),
                ('empty_state_label', models.CharField(blank=True, default='No perspectives published yet.', help_text='Message shown when there are zero published perspectives.', max_length=120)),
            ],
            options={
                'verbose_name': 'Perspectives Index Page',
                'verbose_name_plural': 'Perspectives Index Page',
            },
        ),
        migrations.AddField(
            model_name='connectpage',
            name='email_label',
            field=models.CharField(blank=True, default='Email', help_text='Label above the Email input on the contact form.', max_length=40),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='inquiry_label',
            field=models.CharField(blank=True, default='Reason for reaching out', help_text='Label above the inquiry-type dropdown on the contact form.', max_length=80),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='message_label',
            field=models.CharField(blank=True, default='Message', help_text='Label above the Message textarea on the contact form.', max_length=40),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='message_optional_label',
            field=models.CharField(blank=True, default='(optional)', help_text='Small parenthetical note next to the Message label.', max_length=20),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='name_label',
            field=models.CharField(blank=True, default='Name', help_text='Label above the Name input on the contact form.', max_length=40),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='page_eyebrow',
            field=models.CharField(blank=True, default='Connect', help_text='Small uppercase label above the H1 at the top of the Connect page.', max_length=80),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='page_title',
            field=models.CharField(blank=True, default='Connect', help_text='H1 (page title) at the top of the Connect page.', max_length=120),
        ),
        migrations.AddField(
            model_name='connectpage',
            name='submit_button_label',
            field=models.CharField(blank=True, default='Request a Conversation', help_text='Visible text on the contact-form submit button.', max_length=80),
        ),
        migrations.AddField(
            model_name='enterprisefunction',
            name='responsibilities_label',
            field=models.CharField(blank=True, default='RESPONSIBILITIES', help_text='Small uppercase label above the "Responsibilities" block on the Enterprise Leadership page. Edit per function. Leave blank to fall back to "RESPONSIBILITIES".', max_length=80, verbose_name='"Responsibilities" section label'),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='function_section_eyebrow',
            field=models.CharField(blank=True, default='The Function', help_text='Eyebrow above the "What I lead" heading (the section that holds the three function blocks).', max_length=80),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='impact_label',
            field=models.CharField(blank=True, default='Impact', help_text='Drives both the eyebrow and the H2 of the Impact section on the Enterprise Leadership page.', max_length=80),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='page_eyebrow',
            field=models.CharField(blank=True, default='Enterprise Leadership', help_text='Small uppercase label above the H1 at the top of the Enterprise Leadership page.', max_length=80),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='scope_label',
            field=models.CharField(blank=True, default='Scope', help_text='Drives both the eyebrow and the H2 of the Scope section on the Enterprise Leadership page.', max_length=80),
        ),
        migrations.AddField(
            model_name='enterpriseoverview',
            name='system_integration_eyebrow',
            field=models.CharField(blank=True, default='System Integration', help_text='Eyebrow above the closing-section heading at the bottom of the Enterprise Leadership page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='architecture_eyebrow',
            field=models.CharField(blank=True, default='Architecture', help_text='Eyebrow above the Data → Signals → Decisions block on the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='architecture_heading',
            field=models.CharField(blank=True, default='Data → Signals → Decisions', help_text='H2 above the Data → Signals → Decisions diagram on the Innovation page.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='beacon_eyebrow',
            field=models.CharField(blank=True, default='Beacon Innovation', help_text='Eyebrow above the Beacon Innovation block on the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='beacon_heading',
            field=models.CharField(blank=True, default='Beacon Innovation, LLC', help_text='H2 of the Beacon Innovation block on the Innovation page.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='chief_of_staff_eyebrow',
            field=models.CharField(blank=True, default='AI Chief of Staff', help_text='Eyebrow above the AI Chief of Staff block on the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='chief_of_staff_heading',
            field=models.CharField(blank=True, default='AI Chief of Staff', help_text='H2 of the AI Chief of Staff block on the Innovation page.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_box_1_label',
            field=models.CharField(blank=True, default='Data', help_text='Label inside the FIRST box of the architecture diagram.', max_length=40),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_box_2_label',
            field=models.CharField(blank=True, default='Signals', help_text='Label inside the SECOND box of the architecture diagram.', max_length=40),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_box_3_label',
            field=models.CharField(blank=True, default='Decisions', help_text='Label inside the THIRD box of the architecture diagram.', max_length=40),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_caption_1',
            field=models.CharField(blank=True, default='WHAT SYSTEMS EMIT', help_text='Small uppercase caption under the FIRST diagram box.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_caption_2',
            field=models.CharField(blank=True, default='PATTERNS WORTH WATCHING', help_text='Small uppercase caption under the SECOND diagram box.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='diagram_caption_3',
            field=models.CharField(blank=True, default='ACTION TO TAKE NEXT', help_text='Small uppercase caption under the THIRD diagram box.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='in_practice_eyebrow',
            field=models.CharField(blank=True, default='In Practice', help_text='Eyebrow above the in-practice example beneath the architecture diagram.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='page_eyebrow',
            field=models.CharField(blank=True, default='Innovation', help_text='Small uppercase label above the H1 at the top of the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='what_this_demonstrates_eyebrow',
            field=models.CharField(blank=True, default='What This Demonstrates', help_text='Eyebrow above the closing block on the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='what_this_demonstrates_heading',
            field=models.CharField(blank=True, default='What this demonstrates', help_text='H2 of the closing block on the Innovation page.', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='wlj_eyebrow',
            field=models.CharField(blank=True, default='Whole Life Journey', help_text='Eyebrow above the Whole Life Journey block on the Innovation page.', max_length=80),
        ),
        migrations.AddField(
            model_name='innovationoverview',
            name='wlj_heading',
            field=models.CharField(blank=True, default='Whole Life Journey', help_text='H2 of the Whole Life Journey block on the Innovation page.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='brand_wordmark',
            field=models.CharField(blank=True, default='Danny R. Jenkins', help_text='Wordmark in the top-left of every page header. Also used as the H1 on the resume page.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_approach_eyebrow',
            field=models.CharField(blank=True, default='Approach', help_text='Eyebrow above the Approach block on every case study.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_approach_heading',
            field=models.CharField(blank=True, default='Approach', help_text='H2 of the Approach block on every case study.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_back_link_label',
            field=models.CharField(blank=True, default='← All Case Studies', help_text='Breadcrumb at the top of every case study detail page.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_back_to_all_label',
            field=models.CharField(blank=True, default='← Back to all case studies', help_text='Bottom-of-page back link on every case study.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_chip_suffix',
            field=models.CharField(blank=True, default='Case Study', help_text='Word(s) appended after the category in the chip on a case study detail page (e.g. "Enterprise Case Study").', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_outcome_eyebrow',
            field=models.CharField(blank=True, default='Outcome', help_text='Eyebrow above the Outcome block on every case study.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_outcome_heading',
            field=models.CharField(blank=True, default='Outcome', help_text='H2 of the Outcome block on every case study.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_problem_eyebrow',
            field=models.CharField(blank=True, default='Problem', help_text='Eyebrow above the Problem block on every case study.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_problem_heading',
            field=models.CharField(blank=True, default='The problem', help_text='H2 of the Problem block on every case study.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_role_eyebrow',
            field=models.CharField(blank=True, default='Role', help_text='Eyebrow above the Role block on every case study.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='case_study_role_heading',
            field=models.CharField(blank=True, default='My role', help_text='H2 of the Role block on every case study.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enterprise_column_eyebrow',
            field=models.CharField(blank=True, default='Enterprise Leadership', help_text='Small uppercase label above the left-column heading on the homepage.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_linkedin_label',
            field=models.CharField(blank=True, default='LinkedIn', help_text='Visible text of the LinkedIn link in the footer (the URL is set above).', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_owner_name',
            field=models.CharField(blank=True, default='Danny R. Jenkins', help_text='Name shown after the © year in the footer of every page.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='innovation_column_eyebrow',
            field=models.CharField(blank=True, default='Innovation', help_text='Small uppercase label above the right-column heading on the homepage.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_case_studies_label',
            field=models.CharField(blank=True, default='Case Studies', help_text='Top-nav label for the Case Studies index.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_connect_label',
            field=models.CharField(blank=True, default='Connect', help_text='Top-nav label for the Connect page.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_enterprise_label',
            field=models.CharField(blank=True, default='Enterprise Leadership', help_text='Top-nav label for the Enterprise Leadership page.', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_home_label',
            field=models.CharField(blank=True, default='Home', help_text='Top-nav label for the Home page.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_innovation_label',
            field=models.CharField(blank=True, default='Innovation', help_text='Top-nav label for the Innovation page.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_menu_toggle_label',
            field=models.CharField(blank=True, default='Menu', help_text='Visible text on the mobile nav toggle button.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_perspectives_label',
            field=models.CharField(blank=True, default='Perspectives', help_text='Top-nav label for the Perspectives index.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='nav_profile_label',
            field=models.CharField(blank=True, default='Profile', help_text='Top-nav label for the Profile page.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='perspective_back_link_label',
            field=models.CharField(blank=True, default='← All Perspectives', help_text='Breadcrumb at the top of every perspective detail page.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='perspective_back_to_all_label',
            field=models.CharField(blank=True, default='← Back to all Perspectives', help_text='Bottom-of-page back link on every perspective detail page.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='perspective_closing_eyebrow',
            field=models.CharField(blank=True, default='Closing', help_text='Eyebrow above the closing paragraph on a perspective detail page.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resume_eyebrow_prefix',
            field=models.CharField(blank=True, default='Resume', help_text='Word that prefixes the eyebrow on a resume page (renders as "Resume · <type>").', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resume_print_button_label',
            field=models.CharField(blank=True, default='Print / Save as PDF', help_text='Button text on the resume page that triggers print / save-as-PDF.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vision_eyebrow',
            field=models.CharField(blank=True, default='Vision', help_text='Small uppercase label above the Vision heading on the homepage.', max_length=80),
        ),
    ]
