# Generated by Django 5.0.6 on 2026-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_casestudiesindexpage_perspectivesindexpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudiesindexpage',
            options={'verbose_name': 'Case Studies', 'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order', '-published_at', 'id'], 'verbose_name': 'Case study entry', 'verbose_name_plural': 'Case Studies — Entries'},
        ),
        migrations.AlterModelOptions(
            name='connectpage',
            options={'verbose_name': 'Connect', 'verbose_name_plural': 'Connect'},
        ),
        migrations.AlterModelOptions(
            name='enterprisefunction',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Enterprise Leadership function', 'verbose_name_plural': 'Enterprise Leadership — Functions'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseoverview',
            options={'verbose_name': 'Enterprise Leadership', 'verbose_name_plural': 'Enterprise Leadership'},
        ),
        migrations.AlterModelOptions(
            name='homepagepillar',
            options={'ordering': ['category', 'order', 'id'], 'verbose_name': 'Homepage pillar', 'verbose_name_plural': 'Home — Pillars'},
        ),
        migrations.AlterModelOptions(
            name='innovationoverview',
            options={'verbose_name': 'Innovation', 'verbose_name_plural': 'Innovation'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Profile page', 'verbose_name_plural': 'Profile pages'},
        ),
        migrations.AlterModelOptions(
            name='perspective',
            options={'ordering': ['order', '-published_at', 'id'], 'verbose_name': 'Perspective entry', 'verbose_name_plural': 'Perspectives — Entries'},
        ),
        migrations.AlterModelOptions(
            name='perspectivesindexpage',
            options={'verbose_name': 'Perspectives', 'verbose_name_plural': 'Perspectives'},
        ),
        migrations.AlterModelOptions(
            name='resumeversion',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Resume version', 'verbose_name_plural': 'Resume — Versions'},
        ),
    ]
