# Generated by Django 5.0.6 on 2026-05-04 23:17
#
# Hand-edited to add a conditional data migration: any existing
# ConnectPage row whose submit_button_label is still the original
# default ("Request a Conversation") is updated to "Submit". Rows
# customized by an admin to anything else are left untouched.

from django.db import migrations, models


OLD_DEFAULT = 'Request a Conversation'
NEW_DEFAULT = 'Submit'


def update_submit_label_if_still_old_default(apps, schema_editor):
    ConnectPage = apps.get_model('website', 'ConnectPage')
    ConnectPage.objects.filter(
        submit_button_label=OLD_DEFAULT,
    ).update(submit_button_label=NEW_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_models_for_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpage',
            name='submit_button_label',
            field=models.CharField(blank=True, default='Submit', help_text='Visible text on the contact-form submit button. The form covers multiple inquiry types (resume request, conversation, etc.), so a neutral verb like "Submit" is the safe default.', max_length=80),
        ),
        # Reverse is a no-op so rolling back this migration won't
        # restore "Request a Conversation" on top of any later admin edit.
        migrations.RunPython(
            update_submit_label_if_still_old_default,
            migrations.RunPython.noop,
        ),
    ]
