# Generated by Django 5.0.6 on 2026-05-10 15:37
#
# Hand-edited: appended a RunPython data step that migrates legacy
# ResumeVersion.type codes to their v1 names. The original codes
# 'HR_OPS' and 'TOTAL_REWARDS' are no longer valid choices in the
# new enum (renamed VP_HR / VP_TOTAL_REWARDS for the new audience-
# targeted profile model). Reverse step is a no-op so a rollback
# does not undo the rename.

import tinymce.models
from django.db import migrations, models


LEGACY_TYPE_RENAME = {
    'HR_OPS': 'VP_HR',
    'TOTAL_REWARDS': 'VP_TOTAL_REWARDS',
}

OLD_PRINT_BUTTON_LABEL = 'Print / Save as PDF'
NEW_PRINT_BUTTON_LABEL = 'Download PDF'


def rename_legacy_resume_types(apps, schema_editor):
    ResumeVersion = apps.get_model('website', 'ResumeVersion')
    for old, new in LEGACY_TYPE_RENAME.items():
        ResumeVersion.objects.filter(type=old).update(type=new)


def update_print_button_label_if_old_default(apps, schema_editor):
    """Flip resume_print_button_label from 'Print / Save as PDF' to
    'Download PDF' only if the row still carries the old default. Any
    admin-customized value is preserved."""
    SiteConfig = apps.get_model('website', 'SiteConfig')
    SiteConfig.objects.filter(
        resume_print_button_label=OLD_PRINT_BUTTON_LABEL,
    ).update(resume_print_button_label=NEW_PRINT_BUTTON_LABEL)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_connect_submit_button_default_to_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='featured_case_studies',
            field=models.ManyToManyField(blank=True, help_text='Case studies to surface in the Key Impact Highlights section. Leave empty to omit highlights for this version.', related_name='featured_in_resumes', to='website.casestudy'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='headline',
            field=models.CharField(blank=True, help_text='Per-version headline rendered below the H1 on the resume page (e.g. "Director, Workforce Operations"). Plain text.', max_length=200),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='healthcare_emphasis',
            field=models.PositiveSmallIntegerField(default=5, help_text='0–10. Healthcare operational complexity, AMC context, 24/7 workforce. Set lower for non-healthcare audiences.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='include_innovation',
            field=models.BooleanField(default=True, help_text='When True, the assembled resume includes a Personal AI Systems block sourced from the Innovation Overview. Uncheck for audiences where this is off-message.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='operational_emphasis',
            field=models.PositiveSmallIntegerField(default=5, help_text='0 = no emphasis, 10 = maximum. Operational governance, organizational alignment, payroll reliability.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='summary_source',
            field=models.CharField(choices=[('MANUAL', "Manual — use the Summary section's Content body"), ('HOMEPAGE_SUBHEADLINE', 'Homepage supporting paragraph'), ('ENTERPRISE_HERO_LEAD', 'Enterprise Leadership hero lead'), ('PROFILE_INTRO', 'Profile page intro')], default='MANUAL', help_text='What canonical site content the assembly service uses for the Executive Summary section when its Content body is blank.', max_length=40),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='target_role_notes',
            field=models.TextField(blank=True, help_text='Internal admin-only scratchpad. Never rendered on the public resume. Use for "what to emphasize for this audience" notes.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='technology_emphasis',
            field=models.PositiveSmallIntegerField(default=5, help_text='0–10. Workforce technology leadership, HRIS modernization, systems integration.'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='transformation_emphasis',
            field=models.PositiveSmallIntegerField(default=5, help_text='0–10. Workforce transformation, change leadership, capability building.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resume_location',
            field=models.CharField(blank=True, help_text='City and region for the resume header (e.g. "Knoxville, Tennessee").', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='resume_phone',
            field=models.CharField(blank=True, help_text='Phone number for the resume header (e.g. "423-309-4701"). Plain text; rendered as-is.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_url',
            field=models.CharField(blank=True, default='https://dannyrjenkins.com', help_text='Canonical site URL printed in the resume header. Default is the production domain.', max_length=120),
        ),
        migrations.AlterField(
            model_name='resumesection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Body of this section. Leave blank to let the ResumeAssemblyService compose this section from canonical site content (works for SUMMARY, CURRENT_ROLE, and HIGHLIGHTS). PRIOR_ROLES, EDUCATION, and CUSTOM have no canonical source and require an explicit body here.'),
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='name',
            field=models.CharField(help_text='Internal label for this version (e.g. "VP HR — Recruiter A draft"). Not rendered on the resume page.', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='slug',
            field=models.SlugField(help_text='URL identifier, e.g. "general", "vp-hr", "vp-total-rewards".', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='type',
            field=models.CharField(choices=[('VP_HR', 'VP HR'), ('VP_TOTAL_REWARDS', 'VP Total Rewards'), ('VP_PEOPLE_TECH', 'VP People Technology'), ('ED_HR', 'Executive Director HR'), ('ED_WORKFORCE_OPS', 'Executive Director Workforce Operations'), ('GENERAL', 'General Executive')], default='GENERAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='resume_print_button_label',
            field=models.CharField(blank=True, default='Download PDF', help_text='Button text on the resume page that triggers print / save-as-PDF in the browser.', max_length=80),
        ),
        # Run AFTER all the AlterField operations so the new choices set is
        # already in place when we rewrite legacy values. Reverse is a no-op
        # so rolling back this migration does not restore the legacy codes.
        migrations.RunPython(
            rename_legacy_resume_types,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            update_print_button_label_if_old_default,
            migrations.RunPython.noop,
        ),
    ]
